//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusionGuard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FusionGuard.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damit ich die meine Funktionen auf deinem Kanal ausüben kann, benötige ich deine Genehmigung. Diese erteilst du über folgenden Link:
        ///{URL}.
        /// </summary>
        internal static string AuthorizationCodeUrlSend {
            get {
                return ResourceManager.GetString("AuthorizationCodeUrlSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kanal {UserName} wurde eingetragen..
        /// </summary>
        internal static string ChannelJoined {
            get {
                return ResourceManager.GetString("ChannelJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Kanal {UserName} wurde ausgetragen..
        /// </summary>
        internal static string ChannelLeaved {
            get {
                return ResourceManager.GetString("ChannelLeaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich benötige zuerst Moderator-Rechte um dies auszuführen zu können..
        /// </summary>
        internal static string NeedPermissions {
            get {
                return ResourceManager.GetString("NeedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHTUNG! Hate-Raid! Schreibt bitte keine Nachrichten rein bis wir den Chat wieder freigeben!.
        /// </summary>
        internal static string PanicEnabled {
            get {
                return ResourceManager.GetString("PanicEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Chat ist nun wieder frei! Danke für eure Geduld!.
        /// </summary>
        internal static string PeaceEnabled {
            get {
                return ResourceManager.GetString("PeaceEnabled", resourceCulture);
            }
        }
    }
}
